# ===================== Database Connection (TiDB) =====================
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/elitewear_db?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2,TLSv1.3
spring.datasource.username=46wpiPsTq6RHdYJ.root
spring.datasource.password=5yHramwcCOSpGj4o
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===================== Hibernate / JPA =====================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===================== Server =====================
server.port=8080

# ===================== Email / SMTP =====================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cradles935@gmail.com
spring.mail.password=qwherplaghlpdsgd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true